apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalgroups.multicluster.linkerd.io
spec:
  group: multicluster.linkerd.io
  names:
    categories:
    - external
    kind: ExternalGroup
    listKind: ExternalGroupList
    plural: externalgroups
    singular: externalgroup
    shortNames: [eg]
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: beep boop alien workload
        properties:
          apiVerson:
            description: "APIVersion defines versioned schema"
            type: string
          kind:
            description: "Kind is the kind"
            type: string
          metadata:
            type: object
          spec:
            type: object
            properties:
              template:
                type: object
                description: endpoint template
                properties:
                  metadata:
                    description: Metadata that will be used for all created `ExternalEndpoints`.
                    properties:
                      annotations:
                        additionalProperties:
                          type: string
                        type: object
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  ports:
                    type: array
                    items:
                      type: object
                      properties:
                        port:
                          description: "Name of the port to target"
                          format: int32
                          maximum: 65535
                          minimum: 1
                          type: integer
                        protocol:
                          description: "Protocol"
                          type: string
              probe:
                oneOf:
                - not:
                    anyOf:
                    - required:
                      - httpGet
                - required:
                  - httpGet
                properties:
                  httpGet:
                    properties:
                      host:
                        type: string
                      httpHeaders:
                        items:
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      path:
                        type: string
                      port:
                        type: integer
                      scheme:
                        type: string
                    required:
                    - port
                    type: object
                  initialDelaySeconds:
                    format: int32
                    type: integer
                  periodSeconds:
                    format: int32
                    type: integer
                  successThreshold:
                    format: int32
                    type: integer
                  failureThreshold:
                    format: int32
                    type: integer
                  timeoutSeconds:
                    description: Number of seconds after which the probe times out.
                    format: int32
                    type: integer
                type: object
